### ISSUE TITLE
Do you have a plan to update the list?

### ISSUE THREAD

**Issue by becxer** [evanzd/ICLR2021-OpenReviewData#1]
Do you have a plan to update the list?

**Comment by evanzd** [comment]
Hi @becxer , I will update the list when paper decisions are available (Jan 12, 2021).

UPDATE: I have updated the review ratings.

**Comment by lehduong** [comment]
Thanks for your work. In my opinion, it would be great if you could update the list one last time after 30/11 since some delinquent reviewers might update their scores at the last minutes (i.e. 30/11 Everywhere on Earth?).

**Comment by evanzd** [comment]
Hi @lehduong , thanks for your information. I have updated the ratings to reflect the finalized ratings.

**Comment by evanzd** [comment]
The final decisions have been updated and I will close this issue. Thanks for everyone's interest in this repo!
