### ISSUE TITLE
ICLR 2022 update!

### ISSUE THREAD

**Issue by Jeff-LiangF** [evanzd/ICLR2021-OpenReviewData#2]
Hey, thanks for this awesome repo! Are you planning to get ICLR 2022 ratings recently? They were available one hour ago. I think it might be a good time to update. Looking forward to your reply. Thanks.

**Comment by kashif** [comment]
see PR #3

**Comment by Jeff-LiangF** [comment]
@kashif Thanks, really appreciate it! I'll close this issue.
